backend:
  name: git-gateway
  branch: main
media_folder: "assets"
public_folder: "/assets"
collections:
  - name: "nav-items"
    label: "Navigation Items"
    folder: "content/nav-items"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Icon", name: "icon", widget: "string"}
  - name: "tables"
    label: "Tables"
    folder: "content/tables"
    create: true
    fields:
      - {label: "Table ID", name: "tableId", widget: "string"}
      - {label: "Rows", name: "rows", widget: "list", fields: [
          {label: "Name", name: "name", widget: "string"},
          {label: "Website", name: "website", widget: "string"},
          {label: "Twitter", name: "twitter", widget: "string"},
          {label: "Category", name: "category", widget: "string"},
          {label: "Tasks/Actions", name: "tasks", widget: "string"},
          {label: "Importance", name: "importance", widget: "select", options: ["★★★★★", "★★★★☆", "★★★☆☆", "★★☆☆☆", "★☆☆☆☆"]}
        ]}
