backend:
  name: github
  repo: your-username/alpha-hub
media_folder: "assets" # 上传图片等媒体文件存放的文件夹
public_folder: "/assets"
collections:
  - name: "nav-items" # 导航栏项
    label: "Navigation Items"
    folder: "content/nav-items"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Icon", name: "icon", widget: "string"} # 可以使用 emoji 或图片 URL
  - name: "tables" # 表格内容
    label: "Tables"
    folder: "content/tables"
    create: true
    fields:
      - {label: "Table ID", name: "tableId", widget: "string"} # 对应导航项的表格 ID
      - {label: "Rows", name: "rows", widget: "list", fields: [
          {label: "Name", name: "name", widget: "string"},
          {label: "Website", name: "website", widget: "string"},
          {label: "Twitter", name: "twitter", widget: "string"},
          {label: "Category", name: "category", widget: "string"},
          {label: "Tasks/Actions", name: "tasks", widget: "string"},
          {label: "Importance", name: "importance", widget: "select", options: ["★★★★★", "★★★★☆", "★★★☆☆", "★★☆☆☆", "★☆☆☆☆"]}
        ]}